name: repolint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: articulate/actions-markdownlint@v1.1.0
        # with:
        #   # markdownlint config file
        #   config: # optional
        #   # Markdown files to scan
        #   files: # optional, default is **/*.{md,markdown}
        #   # Files or directories to ignore
        #   ignore: # optional
        #   # Try to fix basic errors
        #   fix: # optional
